services:
  fastapi:
    build:
      context: ./FastAPI
      dockerfile: Dockerfile
    container_name: market_fastapi
    volumes:
      - ./airflow/data:/app/airflow/data
    ports:
      - "8000:8000"
    command: uvicorn app:app --host 0.0.0.0 --port 8000
    restart: unless-stopped

  streamlit:
    build:
      context: ./streamlit
      dockerfile: Dockerfile
    container_name: market_streamlit
    depends_on:
      - fastapi
    environment:
      API_BASE_URL: http://fastapi:8000
    ports:
      - "8501:8501"
    command: streamlit run app.py --server.address 0.0.0.0 --server.port 8501
    restart: unless-stopped
