CREATE SCHEMA IF NOT EXISTS raw;
CREATE SCHEMA IF NOT EXISTS intermediate;
CREATE SCHEMA IF NOT EXISTS mart;

GRANT USAGE, CREATE ON SCHEMA raw TO airflow;
GRANT USAGE, CREATE ON SCHEMA intermediate TO airflow;
GRANT USAGE, CREATE ON SCHEMA mart TO airflow;
